mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
        url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
        url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
        ]
        #old method, before generic views
        #url(r'^$', views.index, name='index'),
        #url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
        #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
        #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
        #]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
     question_text = models.CharField(max_length=200)
     pub_date = models.DateTimeField('date published')
     def __str__(self):
         return self.question_text
     def was_published_recently(self):
         now = timezone.now()
         return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice
# Create your views here.

#def index(request):
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    context = {'latest_question_list': latest_question_list}
#    return render(request, 'polls/index.html', context)

#CHANGE to generic view
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions"""
        return Question.objects.order_by('-pub_date')[:5]

#def detail(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/detail.html', {'question':question})

#CHANGE to generic view
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/results.html', {'question':question})

#CHANGE to generic view
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        #Show the voting form again
        return render(request, "polls/detail.html", {
            'question':question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        #Prevent double POST from back button via HttpResponseRedirect to results view
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<h1>{{ question.question_text}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method='post'>
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type='radio' name='choice' id='choice{{ forloop.counter }}' value="{{ choice.id }}" />
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
	{% endfor %}
	<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Quiz Index</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  {% load static %}
  <link href="{% static 'polls/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'polls/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Nuclear Engineering</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">My Account</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">My Account</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text">Quiz Index</h1>

      <!-- QUIZ CARDS HERE -->
      <div class="col s12 m7">
	<div class="card horizontal">
	  <div class="card-image">
	    <img src="https://www.energy.gov/sites/prod/files/styles/borealis_default_hero_respondlarge/public/nuclear_reactor_technologies_home.png?itok=LOFDpImp">
	  </div>
	  <div class="card-stacked">
	    <div class="card-content">
	      <p>This quiz will test your grasp of the basics</p>
	    </div>
	    <div class="card-action">
	      <a href="#">Take this quiz</a>
	    </div>
	  </div>
	</div>
	<div class="card horizontal">
	  <div class="card-image">
	    <img src="https://www.energy.gov/sites/prod/files/styles/borealis_default_hero_respondlarge/public/nuclear_reactor_technologies_home.png?itok=LOFDpImp">
	  </div>
	  <div class="card-stacked">
	    <div class="card-content">
	      <p>This quiz tests some intermediate knowledge</p>
	    </div>
	    <div class="card-action">
	      <a href="#">Take this quiz</a>
	    </div>
	  </div>
	</div>
  </div>
      <div class="row center">
        <a href="" id="download-button" class="btn-large waves-effect waves-light orange">See Your Progress</a>
      </div>
      <br><br>

    </div>
  </div>


  <footer class="page-footer orange">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">Just a test footer. Class links can go here.</p>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Contact</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">Course Attribution</div>
    </div>
    <div class="footer-copyright">
      <div class="container">Made with Django and Materialize</div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'polls/materialize.js' %}"></script>
  <script src="{% static 'polls/init.js' %}"></script>

  </body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again?</a>